import { VideoConfig } from '../src/yukkuri/yukkuriVideoConfig';

// This file is auto-generated by scripts/generateYukkuriVoiceFiles.ts
// Do not edit manually - edit playground.tsx instead

export const PlaygroundConfig: VideoConfig = {
  "sections": [
    {
      "title": "Playground",
      "bgmSrc": "/audio/bgm/2_23_AM_2.mp3",
      "fromFramesMap": {
        "0": 30,
        "1": 129,
        "2": 258
      },
      "talks": [
        {
          "text": "これは新しい構成のテストだぜ",
          "speaker": "marisa",
          "id": "e47b1416d90b49fc9f4bffdd6549bdcf",
          "audioDurationFrames": 85,
          "image": {
            "src": "/image/remotion-logo.png"
          }
        },
        {
          "text": "スライド番号を指定して画像を切り替えられるんだ",
          "speaker": "marisa",
          "id": "93afbce43198453d9b86a66c85c5660e",
          "audioDurationFrames": 115,
          "image": {
            "src": "/image/react-logo.png"
          }
        },
        {
          "text": "SEも再生できるぞ",
          "speaker": "marisa",
          "id": "76f38ed596244881abc41c28f1d387b3",
          "audioDurationFrames": 65,
          "image": {
            "src": "/image/html_css_javascript.jpeg"
          }
        }
      ],
      "totalFrames": 338,
      "kuchipakuMap": {
        "frames": [],
        "amplitude": []
      },
      "reimuKuchipakuMap": {
        "frames": [],
        "amplitude": []
      },
      "marisaKuchipakuMap": {
        "frames": [],
        "amplitude": []
      },
      "beforeMovieFrames": 0,
      "afterMovieFrames": 0
    }
  ]
};
